---
title: Endless Apps
summary: Learning and educational apps created specifically for Endless OS
image: "/images/endless.png"
separator: "&sdot;"
baseurl: ""
color:
  primary: "#f15a22"
  primary-text: "#fff"

collections:
  apps:
    title: Apps
    output: true
    # Omit the trailing slash to create slightly cleaner links and make it a bit
    # easier to grab the app ID off the end of the URL. This causes Jekyll to
    # generate pages as `com.example.app.html` instead of `com.example.app/index.html`.
    # Since Jekyll and GitHub Pages allow omitting the extension, URLs become
    # `/com.example.app` instead of `/com.example.app/`. Jekyll and GitHub Pages
    # still redirect `/com.example.app/` to `/com.example.app` for us.
    permalink: /:path

defaults:
  - scope:
      path: ""
      type: apps
    values:
      layout: app

markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
