---
title: Endless Apps
summary: Learning and educational apps created specifically for Endless OS
image: "/images/endless.png"
separator: "&sdot;"
baseurl: "/"
color:
  primary: "#f15a22"
  primary-text: "#fff"

collections:
  apps:
    title: Apps
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: apps
    values:
      layout: app

markdown: kramdown

permalink: pretty
sass:
  style: compressed

plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
