---

name: Update Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Weekly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # Not needed with a .ruby-version file
          bundler-cache: true

      - name: Build
        run: |
          sudo apt update && sudo apt install ruby-nokogiri
          gem install nokogiri -- --use-system-libraries
          ruby ./generate-eos-apps.rb

      - name: Commit
        run: |
          FILES_CHANGED=$(git diff --name-only | wc -l)
          if [[ $FILES_CHANGED != 0 ]]; then
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            git commit -m "Automatic update of data" -a
          fi

      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
