---

name: Regenerate App Data

on:
  push:
    branches:
      - main
    paths:
      - 'appstream.xml'
      - 'generate-eos-apps.rb'
      - 'images/icons/'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install ruby-nokogiri git

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          rm _apps/*
          ruby ./generate-eos-apps.rb

      - name: Commit
        run: |
          FILES_CHANGED=$(git diff --name-only | wc -l)
          if [[ $FILES_CHANGED != 0 ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            git commit -m "Automatic update of data" -a
            git push
          fi
